spring:
  application:
    name: media
  h2:
    console:
      enabled:
        true
  datasource:
    url:
      jdbc:h2:mem:test
  jpa:
    show-sql:
      true
    properties:
      hibernate:
        format_sql:
          true